# def habilitarNotificar(self):
#         self.btn_investigar.setEnabled(False)
#         self.btn_consultar.setEnabled(False)
#         self.btn_relatorio.setEnabled(False)
#
#         self.btn_usuarios.setEnabled(False)
#         self.btn_buscarMv.setEnabled(True)
#         self.btn_editarNoti.setEnabled(False)
#         self.rb_mt.setEnabled(True)
#         self.rb_sn.setEnabled(True)
#
#         self.txt_codPacient.clear()
#         self.txt_nmPacient.clear()
#         self.dt_nascimento.text()
#         self.cb_sex.setCurrentIndex(-1)
#         self.cb_seto.setCurrentIndex(-1)
#         self.txt_leit.clear()
#         self.dt_internacao.text
#         self.txt_diagnostic.clear()
#         self.txt_tratamento.clear()
#         self.dt_evento.text()
#         self.dt_notificacao.text()
#         self.txt_consultaNoti.clear()
#         #self.ck_tecno.setCheckState(False)
#         #self.ck_farma.setCheckState(False)
#         #self.ck_hemo.setCheckState(False)
#         self.chk_nsp.setCheckState(False)
#         #self.ck_ccih.setCheckState(False)
#         self.cb_rac.setCurrentIndex(-1)
#
#         self.dt_evento.text()
#         self.dt_internacao.text()
#         self.ck_falha_id.setCheckState(False)
#         self.ck_falha_comu.setCheckState(False)
#         self.ck_falha_oxi.setCheckState(False)
#         self.ck_falha_sonda.setCheckState(False)
#         self.ck_falha_nutri.setCheckState(False)
#         self.ck_falha_hemo.setCheckState(False)
#         self.ck_falha_med.setCheckState(False)
#         self.ck_falha_usu.setCheckState(False)
#         self.ck_falha_anest.setCheckState(False)
#         self.ck_falha_cirurg.setCheckState(False)
#         self.ck_falha_dispo.setCheckState(False)
#         self.ck_queda_hosp.setCheckState(False)
#         self.ck_outros.setCheckState(False)
#         self.ck_ulcera.setCheckState(False)
#         self.ck_infeccao.setCheckState(False)
#         self.ck_inadequada.setCheckState(False)
#         self.ck_higiene_paciente.setCheckState(False)
#         self.ck_neonato.setCheckState(False)
#         self.ck_vaginal.setCheckState(False)
#         self.ck_cesariana.setCheckState(False)
#         self.ck_atendimento.setCheckState(False)
#         self.ck_conflito.setCheckState(False)
#         self.ck_evasao.setCheckState(False)
#         self.ck_sentinela.setCheckState(False)
#         self.ck_queimadura.setCheckState(False)
#         self.txt_ocorrencia.toPlainText()
#         #self.cb_houve_2.setCurrentIndex(-1)
#
#         self.cb_dan.setFrame(False)
#
#         self.txt_como.clear()
#         self.txt_quem.clear()
#         self.txt_acao.clear()
#         self.txt_identificacao.clear()
#
#         self.txt_codPacient.setEnabled(True)
#         self.cb_seto.setEnabled(True)
#         self.txt_leit.setEnabled(True)
#         self.dt_internacao.setEnabled(True)
#         self.txt_diagnostic.setEnabled(True)
#         self.txt_tratamento.setEnabled(True)
#         self.dt_evento.setEnabled(True)
#         #self.ds_outros.setEnabled(True)
#         #self.dt_notificacao.setEnabled(True)
#         #self.ck_tecno.setEnabled(True)
#         #self.ck_farma.setEnabled(True)
#         #self.ck_hemo.setEnabled(True)
#         self.chk_nsp.setEnabled(True)
#         #self.ck_ccih.setEnabled(True)
#
#         self.ck_falha_id.setEnabled(True)
#         self.ck_falha_comu.setEnabled(True)
#         self.ck_falha_oxi.setEnabled(True)
#         self.ck_falha_sonda.setEnabled(True)
#         self.ck_falha_nutri.setEnabled(True)
#         self.ck_falha_hemo.setEnabled(True)
#         self.ck_falha_med.setEnabled(True)
#         self.ck_falha_usu.setEnabled(True)
#         self.ck_falha_anest.setEnabled(True)
#         self.ck_falha_cirurg.setEnabled(True)
#         self.ck_falha_dispo.setEnabled(True)
#         self.ck_queda_hosp.setEnabled(True)
#         self.ck_outros.setEnabled(True)
#         self.ck_ulcera.setEnabled(True)
#         self.ck_infeccao.setEnabled(True)
#         self.ck_inadequada.setEnabled(True)
#         self.ck_higiene_paciente.setEnabled(True)
#         self.ck_neonato.setEnabled(True)
#         self.ck_vaginal.setEnabled(True)
#         self.ck_cesariana.setEnabled(True)
#         self.ck_atendimento.setEnabled(True)
#         self.ck_conflito.setEnabled(True)
#         self.ck_evasao.setEnabled(True)
#         self.ck_sentinela.setEnabled(True)
#         self.ck_queimadura.setEnabled(True)
#         #self.cb_houve_2.setEnabled(True)
#         self.txt_ocorrencia.setEnabled(True)
#         #self.cb_dan.setEnabled(True)
#
#         self.rb_dano_nao.setEnabled(True)
#         self.rb_dano_sim.setEnabled(True)
#         self.rb_dano_SI.setEnabled(True)
#
#         #self.cb_houve_2.setEnabled(True)
#         self.txt_como.setEnabled(True)
#         self.txt_acao.setEnabled(True)
#         self.txt_quem.setEnabled(True)
#         self.txt_identificacao.setEnabled(True)
#         self.btn_salva_noti.setEnabled(True)
#         self.btn_cancela_noti.setEnabled(True)
#         self.btn_pesquisarNoti.setEnabled(False)
#         self.txt_consultaNoti.setEnabled(False)
#
#
# def desabilitarLimparCampos(self):
#
#         self.txt_codPacient.clear()
#         self.txt_nmPacient.clear()
#         self.dt_nascimento.text()
#         self.cb_sex.setCurrentIndex(-1)
#         self.cb_seto.setCurrentIndex(-1)
#         self.txt_leit.clear()
#         self.dt_internacao.text()
#         self.txt_diagnostic.clear()
#         self.txt_tratamento.clear()
#         self.dt_evento.text()
#         self.dt_notificacao.text()
#         self.txt_consultaNoti.clear()
#         self.txt_ocorrencia.clear()
#
#         self.rb_mt.setChecked(False)
#         self.rb_sn.setChecked(False)
#
#
#         self.chk_nsp.setCheckState(False)
#
#         self.cb_rac.setCurrentIndex(-1)
#
#
#         self.dt_evento.text()
#         self.dt_notificacao.text()
#         self.ck_falha_id.setCheckState(False)
#         self.ck_falha_comu.setCheckState(False)
#         self.ck_falha_oxi.setCheckState(False)
#         self.ck_falha_sonda.setCheckState(False)
#         self.ck_falha_nutri.setCheckState(False)
#         self.ck_falha_hemo.setCheckState(False)
#         self.ck_falha_med.setCheckState(False)
#         self.ck_falha_usu.setCheckState(False)
#         self.ck_falha_anest.setCheckState(False)
#         self.ck_falha_cirurg.setCheckState(False)
#         self.ck_falha_dispo.setCheckState(False)
#         self.ck_queda_hosp.setCheckState(False)
#         self.ck_outros.setCheckState(False)
#         self.ck_ulcera.setCheckState(False)
#         self.ck_infeccao.setCheckState(False)
#         self.ck_inadequada.setCheckState(False)
#         self.ck_higiene_paciente.setCheckState(False)
#         self.ck_neonato.setCheckState(False)
#         self.ck_vaginal.setCheckState(False)
#         self.ck_cesariana.setCheckState(False)
#         self.ck_atendimento.setCheckState(False)
#         self.ck_conflito.setCheckState(False)
#         self.ck_evasao.setCheckState(False)
#         self.ck_sentinela.setCheckState(False)
#         self.ck_queimadura.setCheckState(False)
#         self.txt_ocorrencia.toPlainText()
#         #self.cb_houve_2.setCurrentIndex(-1)
#         self.cb_dan.setCurrentIndex(-1)
#         self.txt_como.clear()
#         self.txt_quem.clear()
#         self.txt_acao.clear()
#         self.txt_identificacao.clear()
#         self.rb_mt.setEnabled(False)
#         self.rb_sn.setEnabled(False)
#
# #        self.rb_sn.setEnabled(False)
#
#         self.txt_codPacient.setEnabled(False)
#         self.dt_nascimento.setEnabled(False)
#         self.cb_sex.setEnabled(False)
#         self.cb_seto.setEnabled(False)
#         self.txt_leit.setEnabled(False)
#         self.dt_internacao.setEnabled(False)
#         self.txt_diagnostic.setEnabled(False)
#         self.txt_tratamento.setEnabled(False)
#         self.dt_evento.setEnabled(False)
#         self.dt_notificacao.setEnabled(False)
#
#
#         self.chk_nsp.setEnabled(False)
#
#
#         self.cb_rac.setEnabled(False)
#
#
#         self.rb_dano_nao.setEnabled(False)
#         self.rb_dano_sim.setEnabled(False)
#         self.rb_dano_SI.setEnabled(False)
#
#         self.ck_falha_id.setEnabled(False)
#         self.ck_falha_comu.setEnabled(False)
#         self.ck_falha_oxi.setEnabled(False)
#         self.ck_falha_sonda.setEnabled(False)
#         self.ck_falha_nutri.setEnabled(False)
#         self.ck_falha_hemo.setEnabled(False)
#         self.ck_falha_med.setEnabled(False)
#         self.ck_falha_usu.setEnabled(False)
#         self.ck_falha_anest.setEnabled(False)
#         self.ck_falha_cirurg.setEnabled(False)
#         self.ck_falha_dispo.setEnabled(False)
#         self.ck_queda_hosp.setEnabled(False)
#         self.ck_outros.setEnabled(False)
#         self.ck_ulcera.setEnabled(False)
#         self.ck_infeccao.setEnabled(False)
#         self.ck_inadequada.setEnabled(False)
#         self.ck_higiene_paciente.setEnabled(False)
#         self.ck_neonato.setEnabled(False)
#         self.ck_vaginal.setEnabled(False)
#         self.ck_cesariana.setEnabled(False)
#         self.ck_atendimento.setEnabled(False)
#         self.ck_conflito.setEnabled(False)
#         self.ck_evasao.setEnabled(False)
#         self.ck_sentinela.setEnabled(False)
#         self.ck_queimadura.setEnabled(False)
#
#         #self.cb_houve_2.setEnabled(False)
#         self.cb_dan.setEnabled(False)
#         self.txt_ocorrencia.setEnabled(False)
#         self.txt_como.setEnabled(False)
#         self.txt_acao.setEnabled(False)
#         self.txt_identificacao.setEnabled(False)
#         self.txt_quem.setEnabled(False)
#         self.ds_outros.setEnabled(False)
#         self.btn_salva_noti.setEnabled(False)
#         self.btn_cancela_noti.setEnabled(False)
#         self.btn_pesquisarNoti.setEnabled(True)
#         self.txt_consultaNoti.setEnabled(True)
#         self.btn_investigar.setEnabled(True)
#         self.btn_consultar.setEnabled(True)
#         self.btn_relatorio.setEnabled(True)
#         self.btn_buscarMv.setEnabled(False)
#
# def editandoNotificacao(self):
#         self.cb_seto.setEnabled(True)
#         self.txt_leit.setEnabled(True)
#         self.dt_internacao.setEnabled(True)
#         self.txt_diagnostic.setEnabled(True)
#         self.txt_tratamento.setEnabled(True)
#         self.dt_evento.setEnabled(True)
#         self.dt_notificacao.setEnabled(True)
#
#         self.chk_nsp.setEnabled(True)
#
#         self.rb_mt.setEnabled(True)
#         self.rb_sn.setEnabled(True)
#         self.btn_buscarMv.setEnabled(True)
#
#
#
#         self.ck_falha_id.setEnabled(True)
#         self.ck_falha_comu.setEnabled(True)
#         self.ck_falha_oxi.setEnabled(True)
#         self.ck_falha_sonda.setEnabled(True)
#         self.ck_falha_nutri.setEnabled(True)
#         self.ck_falha_hemo.setEnabled(True)
#         self.ck_falha_med.setEnabled(True)
#         self.ck_falha_usu.setEnabled(True)
#         self.ck_falha_anest.setEnabled(True)
#         self.ck_falha_cirurg.setEnabled(True)
#         self.ck_falha_dispo.setEnabled(True)
#         self.ck_queda_hosp.setEnabled(True)
#         self.ck_outros.setEnabled(True)
#         self.ck_ulcera.setEnabled(True)
#         self.ck_infeccao.setEnabled(True)
#         self.ck_inadequada.setEnabled(True)
#         self.ck_higiene_paciente.setEnabled(True)
#         self.ck_neonato.setEnabled(True)
#         self.ck_vaginal.setEnabled(True)
#         self.ck_cesariana.setEnabled(True)
#         self.ck_atendimento.setEnabled(True)
#         self.ck_conflito.setEnabled(True)
#         self.ck_evasao.setEnabled(True)
#         self.ck_sentinela.setEnabled(True)
#         self.ck_queimadura.setEnabled(True)
#
#
#
#         self.rb_dano_SI.setEnabled(True)
#         self.rb_dano_nao.setEnabled(True)
#         self.rb_dano_sim.setEnabled(True)
#
#
#         self.txt_ocorrencia.setEnabled(True)
#         self.txt_identificacao.setEnabled(True)
#         self.txt_como.setEnabled(True)
#         self.txt_acao.setEnabled(True)
#         self.txt_quem.setEnabled(True)
#         self.btn_salva_noti.setEnabled(False)
#         self.btn_cancela_noti.setEnabled(True)
#         self.btn_alterar.setEnabled(True)
#
#         self.btn_consultar.setEnabled(False)
#