# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resumo_notifica.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget, QMessageBox

from FNEA.bd.conn import conexaoBD


class Ui_resumo(object):
    def setupUi(self, resumo):
        resumo.setObjectName("resumo")
        resumo.resize(881, 258)
        resumo.setStyleSheet("background-color: rgba(255,255,255,255);\n"
"border-radius: 10px;\n"
"border: 3px;\n"
"border-color: rgb(121, 121, 121);")
        self.centralwidget = QtWidgets.QWidget(resumo)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_69 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(12)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_2.addWidget(self.label_69)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_67 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_2.addWidget(self.label_67)
        self.txt_codPaciente = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_codPaciente.setEnabled(False)
        self.txt_codPaciente.setMinimumSize(QtCore.QSize(60, 0))
        self.txt_codPaciente.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        self.txt_codPaciente.setFont(font)
        self.txt_codPaciente.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px")
        self.txt_codPaciente.setObjectName("txt_codPaciente")
        self.horizontalLayout_2.addWidget(self.txt_codPaciente)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_68 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_3.addWidget(self.label_68)
        self.txt_nmPaciente = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nmPaciente.setEnabled(False)
        self.txt_nmPaciente.setMinimumSize(QtCore.QSize(250, 0))
        self.txt_nmPaciente.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        self.txt_nmPaciente.setFont(font)
        self.txt_nmPaciente.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px")
        self.txt_nmPaciente.setText("")
        self.txt_nmPaciente.setObjectName("txt_nmPaciente")
        self.horizontalLayout_3.addWidget(self.txt_nmPaciente)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_81 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        self.label_81.setFont(font)
        self.label_81.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout.addWidget(self.label_81)
        self.txt_nunnoti = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nunnoti.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        self.txt_nunnoti.setFont(font)
        self.txt_nunnoti.setStyleSheet("\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px\n"
"")
        self.txt_nunnoti.setText("")
        self.txt_nunnoti.setObjectName("txt_nunnoti")
        self.horizontalLayout.addWidget(self.txt_nunnoti)
        self.btn_pesquisarNoti = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pesquisarNoti.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(8)
        font.setBold(False)
        self.btn_pesquisarNoti.setFont(font)
        self.btn_pesquisarNoti.setStyleSheet("QPushButton#btn_pesquisarNoti{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(0, 39,119, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_pesquisarNoti:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_pesquisarNoti:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Imagem/historia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pesquisarNoti.setIcon(icon)
        self.btn_pesquisarNoti.setIconSize(QtCore.QSize(24, 24))
        self.btn_pesquisarNoti.setObjectName("btn_pesquisarNoti")
        self.horizontalLayout.addWidget(self.btn_pesquisarNoti)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.txt_resumo_ocorrencia = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_resumo_ocorrencia.setEnabled(False)
        self.txt_resumo_ocorrencia.setMinimumSize(QtCore.QSize(400, 70))
        self.txt_resumo_ocorrencia.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        self.txt_resumo_ocorrencia.setFont(font)
        self.txt_resumo_ocorrencia.setStyleSheet("background-color: rgba(10,0,0,50);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px")
        self.txt_resumo_ocorrencia.setObjectName("txt_resumo_ocorrencia")
        self.verticalLayout.addWidget(self.txt_resumo_ocorrencia)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.btn_sair_resumo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair_resumo.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(8)
        font.setBold(False)
        self.btn_sair_resumo.setFont(font)
        self.btn_sair_resumo.setStyleSheet("QPushButton#btn_sair_resumo{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(0, 39,119, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_sair_resumo:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682,x2:1,y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#btn_sair_resumo:pressed{\n"
"    padding-left:5px;\n"
"    padding -top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Imagem/remover (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sair_resumo.setIcon(icon1)
        self.btn_sair_resumo.setIconSize(QtCore.QSize(24, 24))
        self.btn_sair_resumo.setObjectName("btn_sair_resumo")
        self.verticalLayout_3.addWidget(self.btn_sair_resumo)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        resumo.setCentralWidget(self.centralwidget)

        self.retranslateUi(resumo)
        QtCore.QMetaObject.connectSlotsByName(resumo)
        resumo.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)

    def retranslateUi(self, resumo):
        _translate = QtCore.QCoreApplication.translate
        resumo.setWindowTitle(_translate("resumo", "RESUMO DA NOTIFICAÇÃO"))
        self.label_69.setText(_translate("resumo", "RESUMO DA NOTIFICAÇÃO"))
        self.label_67.setText(_translate("resumo", "Cod.Paciente:"))
        self.label_68.setText(_translate("resumo", "Paciente:"))
        self.label_81.setText(_translate("resumo", "Número da notificação"))
        self.btn_pesquisarNoti.setToolTip(_translate("resumo", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt;\">PESQUISAR NOTIFICAÇÃO</span></p></body></html>"))
        self.btn_pesquisarNoti.setText(_translate("resumo", "P E S Q U I S A R"))
        self.btn_sair_resumo.setText(_translate("resumo", "S A I R"))
        
        self.btn_pesquisarNoti.clicked.connect(self.ResumoNotificacao)
        self.btn_sair_resumo.clicked.connect(resumo.close)
        
        
    def ResumoNotificacao(self):
                global cd_notificacao

                database="notiproducao"
                con = conexaoBD(bd = database)

                
                notificacao = self.txt_nunnoti.text()

                if not self.txt_nunnoti.text():
                        msg = QMessageBox()
                        msg.setWindowTitle("AVISO")
                        msg.setText("INFORME O CODIGO DA NOTIFICAÇÃO")
                        msg.setIcon(QMessageBox.Warning)
                        msg.exec()
                        return False

                resul = con.consultar("SELECT n.cd_paciente,n.nm_paciente,n.ds_ocorrencia FROM notificacao n WHERE n.cd_notificacao = "+str(notificacao)+"")

                cd_notificacao = notificacao
                
                if resul == []:
                        msg = QMessageBox()
                        msg.setWindowTitle("AVISO")
                        msg.setText("NOTIFICAÇÃO NÃO ENCONTRADA!")
                        msg.setIcon(QMessageBox.Warning)
                        msg.exec()

                if(resul):
                        for dt in resul:              
                                self.txt_codPaciente.setText(str(dt[0]))
                                self.txt_nmPaciente.setText(str(dt[1]))
                                self.txt_resumo_ocorrencia.setText(str(dt[2]))